// This file was generated by img2gb, DO NOT EDIT

#ifndef _LOGO_RGB_TILEMAP_H
#define _LOGO_RGB_TILEMAP_H

extern const UINT8 LOGO_RGB_TM[];
#define LOGO_RGB_TM_WIDTH 20
#define LOGO_RGB_TM_HEIGHT 18


#endif
