// This file was generated by img2gb, DO NOT EDIT

#ifndef _SPLASHSCREEN_TILEMAP_H
#define _SPLASHSCREEN_TILEMAP_H

extern const UINT8 SPLASH_TM[];
#define SPLASH_TM_WIDTH 20
#define SPLASH_TM_HEIGHT 18


#endif
