// This file was generated by img2gb, DO NOT EDIT

#ifndef _STUDIO_TILEMAP_H
#define _STUDIO_TILEMAP_H

extern const UINT8 STUDIO_TM[];
#define STUDIO_TM_WIDTH 32
#define STUDIO_TM_HEIGHT 18


#endif
